# Setup
title:               "errorfixie 블로그"
tagline:             '이것저것'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://errorfixie.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              "강대국"
  url:               ""
  email:             "eornr1129@naver.com"

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

remote_theme : poole/lanyon